# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Europe/Brussels"
    ignore:
      - dependency-name: "crate-ci/typos"
        update-types: ["version-update:semver-patch"]
