name: "Format Check"

on:
  push:
    branches:
      - 'master'
      - 'release-'
    tags: '*'
  pull_request:

jobs:
  format-check:
    name: "Format Checks"
    uses: "SciML/.github/.github/workflows/format-suggestions-on-pr.yml@014c98428fa1165dbf01478156359253f984fb0a"
